[codes]
english = 'en'
german = 'de'
french = 'fr'
spanish = 'es'
russian = 'ru'
japanese = 'ja'
chinese = 'zh'
italian = 'it'
portuguese = 'pt'
polish = 'pl'
dutch = 'nl'
ukrainian = 'uk'
swedish = 'sv'
cebuano = 'ceb'
arabic = 'ar'
persian = 'fa'
vietnamese = 'vi'
turkish = 'tr'
korean = 'ko'
indonesian = 'id'
czech = 'cs'
hebrew = 'he'
hungarian = 'hu'
finnish = 'fi'
norwegian = 'no'
danish = 'da'
romanian = 'ro'
greek = 'el'
serbian = 'sr'
catalan = 'ca'

[aliases]
german = ['Deutsch']
french = ['Français']
spanish = ['Español']
russian = ['Русский']
japanese = ['日本語']
chinese = ['中文']
italian = ['Italiano']
portuguese = ['Português']
polish = ['Polski']
dutch = ['Nederlands']
ukrainian = ['Українська']
swedish = ['Svenska']
cebuano = ['Bisaya', 'Sinugbuanong Binisaya']
arabic = ['العربية']
persian = ['فارسی']
vietnamese = ['Tiếng Việt']
turkish = ['Türkçe']
korean = ['한국어']
indonesian = ['Bahasa Indonesia']
czech = ['Čeština']
hebrew = ['עברית']
hungarian = ['Magyar']
finnish = ['Suomi']
norwegian = ['Norsk', 'Norsk bokmål']
danish = ['Dansk']
romanian = ['Română']
greek = ['Ελληνικά']
serbian = ['Српски']
catalan = ['Català']
