languages = {
  'English': 'en',
  'Ukrainian': 'uk',
  'Українська': 'uk',
  'Russian': 'ru',
  'Русский': 'ru',
  'Polish': 'pl',
  'Polski': 'pl',
  'German': 'de',
  'Deutsch': 'de',
  'Nederlands': 'nl',
  'Dutch': 'nl',
  'Swedish': 'sv',
  'Svenska': 'sv',
  'Spanish': 'es',
  'Español': 'es',
  'French': 'fr',
  'Français': 'fr',
  'Italian': 'it',
  'Italiano': 'it',
  'Japanese': 'ja',
  'Chainese': 'zh',
  'Cebuano': 'ceb',
  'Bisaya': 'ceb'
}